How to create arrays and vectors, the fundamentls stuffs to linear algebra  


In [2]:
import numpy as np

En primer lugar, al igual que definimos las matrices y vectores en la tableta, tenemos que array o arreglo, no es mas que la forma en la cual <br>
podemos presentar las diferentes unidades / bases de el algebra lineal: <br>


Vector & Matriz

In [4]:
#There is a mutiply ways to create vectors an darray the first way is just passing a list:

vector  = np.array([1, 2, 3, 4]) # <-- At this case we show a vector, cause even if we have different elements inside our array, they dont follow the rule of rows, and columns
#print(type(vector))

Arr = np.array([[1, 2], [3, 4]]) #<-- On this one is a matrix
#print(type(Arr))

Las matrices como bien lo vimos, tambien pueden resultar de la combinacion de varios, vectores <br>
que tambien podemos decidir el sentido, si los unimos en forma de tomarlos como columna o filas

In [7]:
# First we need a mutiple vectors
v1 = np.array([1, 2, 4, 6])
v2 = np.array([0, -2, 4, 7])
v3 = np.array([1, 8, -6, 2])

#Then we the built-in function colum_stack
#Usamos funcione de numpy que son colum y row, para definir si queremos unir nuestros vectores en forma de columa, o en forma de vector

Arr = np.column_stack((v1, v2, v3))  # <-- Los une como si fueran en gorma de columna.
print(Arr)

Arr_2 = np.row_stack((v1, v2, v3))
print(Arr_2)

[[ 1  0  1]
 [ 2 -2  8]
 [ 4  4 -6]
 [ 6  7  2]]
[[ 1  2  4  6]
 [ 0 -2  4  7]
 [ 1  8 -6  2]]


Como visualizar la forma:
usando .shape
That give us in way rows, columns

In [16]:
A = np.array([[1,2],[3,4]])
print(A.shape)

(2, 2)


Para acceder a los indices, podemos realizarlo igual que en los arreglos de python, tomando en cueta:
que el primer valor son las filas y el segundo las columnas:

In [19]:
#Accdediendo a la matriz superior:
print(A[0,1]) # En la primera linea , 1 ; El segundo valor.

2


We also can select a subset, subconjunto, utilizando los dos puntos, that depends if we want a column or a row:

In [21]:
A = np.array([[1, 2], [3, 4]])
print(A[:1]) #Imprime la segunda columna

#Just to separate
print("\\\\")

print(A[1:]) # Imprime la segunda fila

#There is a diference if we use print(matrix[:,2]) the comma, or not if we dont use it 
#The codes follows the rule until, as the first row until the second one that shows in the 
#next lines of code:

[[1 2]]
\\
[[3 4]]


In [23]:

# Given vectors
vector_1 = np.array([-2,-6,2,3])
vector_2 = np.array([4,1,-3,8])
vector_3 = np.array([5,-7,9,0])

matrix = np.column_stack((vector_1, vector_2, vector_3))
print(matrix)

print('Just to saw it the diference')

print(matrix[:,2])

print('Just to saw it the diference')

print(matrix[:2])

[[-2  4  5]
 [-6  1 -7]
 [ 2 -3  9]
 [ 3  8  0]]
Just to saw it the diference
[ 5 -7  9  0]
Just to saw it the diference
[[-2  4  5]
 [-6  1 -7]]


# <span style="color:#FFD1DC">Operaciones con Python para algebra lineal</span>.


## <span style="color:#A2D2FF">Multiplicacion de matrices</span>


In [25]:
#Multiplicaciones

#Multiplicacion por un escalar
A = np.array([[1, 4], [5, 7]])
B = 5 * A

print(A)

print('There is the difference:')

print(B)

[[1 4]
 [5 7]]
There is the difference:
[[ 5 20]
 [25 35]]


In [27]:
A = np.array([[1,2],[3,4]])
B = np.array([[-4,-3],[-2,-1]])

# one way to matrix multiply
np.matmul(A,B)
# another way to matrix multiply
A@B

array([[ -8,  -5],
       [-20, -13]])

## <span style="color:#A2D2FF">Sumatoria de matrices</span>


In [26]:
A = np.array([[1, 6], [5, 1]])
B = np.array([[5, 2], [16, 1]])

print(A + B)

[[ 6  8]
 [21  2]]


## <span style="color:#A2D2FF">Producto - Punto</span>


La función producto punto, también conocida como producto escalar, es una operación matemática que toma dos vectores y devuelve un número escalar.

dado dos vectores [a1, b1 , c1] * [a2, b2 , c2] =  a1*a2 + b1*b2 + c1*c2 == 'valor escalar'


v = np.array([-1,-2,-3])
u = np.array([2,2,2])
np.dot(v,u)

¿Para qué sirve?
Medir la Similitud: El producto punto puede ser utilizado para medir la similitud entre dos vectores. Si el resultado es cero, significa que los vectores son perpendiculares entre sí. Si es positivo, indica que los vectores apuntan en una dirección similar, y si es negativo, indica que apuntan en direcciones opuestas.

Proyección: Puedes usar el producto punto para proyectar un vector sobre otro. Esto es útil en física para descomponer fuerzas y en gráficos por computadora para calcular sombras y reflejos.

Machine Learning y Análisis de Datos: En machine learning, el producto punto se utiliza en algoritmos como el SVM (Máquinas de Soporte Vectorial) y en la medición de similitud entre documentos en procesamiento de lenguaje natural.

Física: En física, el producto punto se utiliza para calcular trabajo, donde un vector representa una fuerza y el otro representa un desplazamiento.

# <span style="color:#FFD1DC">Matrices Especiales</span>.


## <span style="color:#A2D2FF">Matriz de identidad</span>


Una matriz de identidad puede ser construida con la funcion de numpy "np.eye()" que toma como argumento un entero

In [29]:
# 4x4 identity matrix
identity = np.eye(4)

print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## <span style="color:#A2D2FF">Matriz Ceros</span>


Una matriz construida con mutiples ceros se puede construir atravez del metodo np.zeros(), que recibe una tupla en la forma (rows, columns), en caso de querer un vector, unicamente 
pasamos un unico valor

In [32]:
zero_vector = np.zeros((5))
print(zero_vector)

matriz_vector =  np.zeros((5,6))
print(f'\n {matriz_vector}')

[0. 0. 0. 0. 0.]

 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


## <span style="color:#A2D2FF">Matriz Transpuesta</span>


Se puede acceder a la transposicion de una matriz usando el atributo .T

Una matriz transpuesta cambia entre columnas y filas

In [1]:
matrix =  np.array([[5, 7, 6], [64, 74, 7]])

matrix.T

print(matrix)
print(f'\n {matrix.T}')

NameError: name 'np' is not defined

In [34]:
#Ex for pracite, solve it:

In [ ]:
# Given
A = np.array([[1,-1,1], [0,1,0], [-1,2,1]])
B = np.array([[0.5,1.5,-0.5], [0,1,0], [0.5,-0.5,0.5]])

print(A@B)
print(f'\n {B@A}')

#Since the matrix product of A and B results in the identity matrix, they are inverses of each other.
print(A.T)
print(f'\n {B.T}')


# <span style="color:#FFD1DC">Operaciones Adicionales de algebra lineal</span>.


## <span style="color:#A2D2FF">np.linalg.norm()</span>


La "norma" (o longitud/magnitud) de un vector se puede encontrar usando np.linalg.norm():

In [36]:
v = np.array([2,-4,1])
v_norm = np.linalg.norm(v)
print(v_norm)

4.58257569495584


## <span style="color:#A2D2FF">Inversa de la matriz cuadrada</span>


La inversa de una matriz cuadrada, si existe, puede encontrarse utilizando np.linalg.inv():


In [37]:
A = np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


## <span style="color:#A2D2FF">np.linalg.solve()</span>


Finally, we can actually solve for unknown variables in a system on linear equations in Ax=b form using np.linalg.solve(), which takes in the A and b parameters. Given:



In [38]:
#Given the next functions
#  x + 4y -  z = -1
# -x - 3y + 2z =  2
# 2x -  y - 2z = -2

# each array in A is an equation from the above system of equations
A = np.array([[1,4,-1],[-1,-3,2],[2,-1,-2]])
# the solution to each equation
b = np.array([-1,2,-2])
# solve for x, y, and z
x,y,z = np.linalg.solve(A,b)

In [ ]:
#If we print((x, y, z)), we see the following output:

#(0, 0, 1.0)

# showing that the solution to the system of equations is:

# x = 0
# y = 0
# z = 1

In [39]:
#Other example
# Given
'''
4x + z = 2
-y + 2z - 3x = 0
.5y - x - 1.5z = -4
'''

A= np.array([[4, 0, 1],[-3, -1, 2],[-1, 0.5, -1.5]])
b = np.array([2, 0, -4])

x,y,z = np.linalg.solve(A,b)
print(x, y, z)


6.0 -62.0 -22.0


#F