In [1]:
import numpy as np

In [2]:
A1 = np.array([[2, -3, 1], [-2, -1, 4], [0, 2, 2]])

A2 = np.array([[3, -2, 1], [1, -1, 2], [-2, 2, 0]])

print(A1@A2)

[[  1   1  -4]
 [-15  13  -4]
 [ -2   2   4]]


What is the angle, in degrees rounded to the nearest whole number, between the following two vectors?



In [3]:
# the followng vectors is what it gives to me
vector_a = [3, -1, 2] 
vector_b = [0, -1, 1]

#we need to use a formula,  producto escalar 
dot_product = np.dot(vector_a, vector_b)

# Calcular las magnitudes de los vectores
magnitude_a = np.linalg.norm(vector_a)
magnitude_b = np.linalg.norm(vector_b)

# Calcular el coseno del ángulo
cos_angle = dot_product / (magnitude_a * magnitude_b)

angle_radians = np.arccos(cos_angle)

# Convertir el ángulo a grados
angle_degrees = np.degrees(angle_radians)

print("Ángulo entre los vectores:", angle_degrees, "grados")


Ángulo entre los vectores: 55.46241621381916 grados


What is the length (magnitude) of the following vector?



In [6]:
import math

vector = np.array([-2, -3, 0, 5, 1])

mag = np.linalg.norm(vector)
print(mag)

# Calculando la magnitud manualmente como la raíz cuadrada de la suma de los cuadrados
mag_sqrt = math.sqrt(sum(x**2 for x in vector))
print("Magnitud usando la raíz cuadrada:", mag_sqrt)

6.244997998398398
Magnitud usando la raíz cuadrada: 6.244997998398398


Solve the following system of equations using Gaussian Elimination

In [11]:
# 2x - 3y + z = 2
# 3X + Y + Z = -1
# -X -2y = 1

# 2x - 3y + z = 2
# 3x + y + z = -1
# -x - 2y + 0z = 1
from fractions import Fraction

equations = np.array([[2, -3, 1], [3, 1, 1], [-1, -2, -1]]) # Añadido el coeficiente 0 para z en la tercera ecuación
results = np.array([2, -1, 1])

x, y, z = np.linalg.solve(equations, results)
print(x, y, z)


print('*' * 100 + '\n')

# Convertir los resultados a fracciones
x_frac = Fraction(x).limit_denominator()
y_frac = Fraction(y).limit_denominator()
z_frac = Fraction(z).limit_denominator()

print(x_frac, y_frac, z_frac)




-0.3333333333333335 -0.6666666666666666 0.6666666666666669
****************************************************************************************************

-1/3 -2/3 2/3


In [12]:
import numpy as np

R = np.array([[1, 3, -4, -8], [4, 0, 2, -3], [7, -2, 1, -1], [-2, -1, 0, 2]])
Q = np.array([[-4, 3, -8, 1], [2, 0, -3, 4], [1, -2, -1, 7], [0, -1, 2, -2]])

R_inv = np.linalg.inv(R)
P = np.dot(Q, R_inv)

print(P)


[[ 0.3902439  -3.48780488  0.53658537 -2.90243902]
 [-0.38211382 -2.77235772  1.01626016 -3.17886179]
 [-0.61788618 -2.22764228  0.98373984 -1.82113821]
 [ 0.2601626   1.67479675 -0.30894309  2.39837398]]
