In [1]:
import numpy as np

In [2]:
A1 = np.array([[2, -3, 1], [-2, -1, 4], [0, 2, 2]])

A2 = np.array([[3, -2, 1], [1, -1, 2], [-2, 2, 0]])

print(A1@A2)

[[  1   1  -4]
 [-15  13  -4]
 [ -2   2   4]]


What is the angle, in degrees rounded to the nearest whole number, between the following two vectors?



In [3]:
# the followng vectors is what it gives to me
vector_a = [3, -1, 2] 
vector_b = [0, -1, 1]

#we need to use a formula,  producto escalar 
dot_product = np.dot(vector_a, vector_b)

# Calcular las magnitudes de los vectores
magnitude_a = np.linalg.norm(vector_a)
magnitude_b = np.linalg.norm(vector_b)

# Calcular el coseno del ángulo
cos_angle = dot_product / (magnitude_a * magnitude_b)

angle_radians = np.arccos(cos_angle)

# Convertir el ángulo a grados
angle_degrees = np.degrees(angle_radians)

print("Ángulo entre los vectores:", angle_degrees, "grados")


Ángulo entre los vectores: 55.46241621381916 grados


What is the length (magnitude) of the following vector?



In [5]:
vector = np.array([-2, -3, 0, 5, 1])

mag = np.linalg.norm(vector)
print(mag)

6.244997998398398
