In [13]:
import numpy as np
import math
from fractions import Fraction # To use fractions


In [2]:

A = np.array([3, -1, 2])
B = np.array([0, -1, 1])

result = np.dot(A, B)

print(result)

3


In [4]:

A = [3, -1, 2]
B = [0, -1, 1]

dot_product = sum(a * b for a, b in zip(A, B))
magnitude_A = math.sqrt(sum(a**2 for a in A))
magnitude_B = math.sqrt(sum(b**2 for b in B))

cos_theta = dot_product / (magnitude_A * magnitude_B)
theta = math.degrees(math.acos(cos_theta))

# Round to the nearest whole number
theta_rounded = round(theta)
theta_rounded

55

In [5]:
# Given matrix R
R = np.array([
    [1, 4, 7, -2],
    [3, 0, -2, -1],
    [-4, 2, 1, 0],
    [-8, -3, -1, 2]
])

# Target matrix
target = np.array([
    [-4, 2, 1, 0],
    [3, 0, -2, -1],
    [-8, -3, -1, 2],
    [1, 4, 7, -2]
])

# Initialize permutation matrix P as an identity matrix
P = np.eye(4)

# Rearrange the rows of P according to the order in which the rows of R appear in the target matrix
for i, row in enumerate(target):
    index = np.where((R == row).all(axis=1))[0][0]
    P[i], P[index] = P[index], P[i].copy()

# Print the permutation matrix P
print(P)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [8]:
# Given matrices
A = np.array([[2, 3], [-2, 0]])
B = np.array([[1, -2], [3, 1]])

# Scalar value
k = 4

# Multiply A by the scalar k and subtract B
result = k * A - B

# Print the result
print(result)

[[  7  14]
 [-11  -1]]


In [10]:
v = np.array([-2, -3, 0, 5, 1])
v_norm = np.linalg.norm(v)
print(v_norm)

6.244997998398398


In [14]:
#Given the next functions
#  2x - 3y + z = 2
#  3x  + y + z = -1
# -x - 2y - z = 1


# each array in A is an equation from the above system of equations
A = np.array([[2, -3, 1],[3, 1, 1],[-1, -2, -1]])
# the solution to each equation
b = np.array([2, -1, 1])
# solve for x, y, and z
x,y,z = np.linalg.solve(A,b)

x_frac = Fraction(x).limit_denominator()
y_frac = Fraction(y).limit_denominator()
z_frac = Fraction(z).limit_denominator()

print(x_frac, y_frac, z_frac)


-1/3 -2/3 2/3


In [19]:
#
A = np.array([[2, 3, 4], [2, 3, 4], [2, 3, 4], [2, 3, 4]])
B = np.array([[1, -2, -1], [1, -2, -1], [1, -2, -1]])
C = np.array([1, 2, 3])

result_temp = A @ B.T
D = result_temp @ C.T

D.shape

(4,)